# Site settings
title: Daye Nam
email: daye.nam@uci.edu
description: "Assistant Professor at UC Irvine.<br/> I study and build intelligent tools for programmers at all levels."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dayenam.com" # the base hostname & protocol for your site
production_url: "https://dayenam.com"
github_username: namdy0429
permalink: /blog/:year/:month/:title.html

twitter:
  username: daye_nam

sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions