name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Workflow is working!"